### PR TITLE
Add support for allOf field

### PR DESCRIPTION
**Pull request by AttilaTheFun**
This PR adds support for the allOf field and an associated unit test.
It does not change the public API of the library, but rather creates a new ObjectSchema by combining the sub-Schema's referenced by the allOf field.

### CODE REVIEW

**Comment by n8chur** [comment]
In order to do things for code generation like create interfaces for schemas that are shared between multiple `allOf` schemas, you would need access to each of the individual schemas in the `allOf` array when consuming the parsed Swagger structure. Since you are merging the `allOf` items into a single `ObjectSchema`, a consumer would be unable to obtain this information when code generating models.

Also, I'm not sure whether enforcing that the schemas are "object" schemas is necessary. `allOf` schemas could be parsed as a new `AllOfSchema` that has a `[Schema]` property (and, in my opinion, ideally a `Metadata` property as well).

I'm hoping to get my PR up today that has `allOf` support included in this way. I'm just waiting on some internal code review at my company before we can open source it. I'll keep bugging the reviewers :)

**Comment by AttilaTheFun** [comment]
Ok sure @n8chur - happy to check out your approach as well.

**Comment by n8chur** [comment]
I opened #6 with my approach for `allOf` support. Let me know what you think!

**Comment by AttilaTheFun** [comment]
Closing this PR in favor of #6

**Pull request closed without merging**
