### PR TITLE
Add support for `allOf`, `x-nullable`, `x-abstract`, `example`, `discriminator`, and more…

### PR DESCRIPTION
**Pull request by n8chur**
- `allOf`
- `x-nullable`
- `discriminator`
- `x-abstract`
- `example`/`x-example`
- Separated Swagger spec files (e.g. Base.json, Models/ModelA.json, Models/ModelB.json, etc.)
- Moved test fixture to a file
- Added more unit tests

### CODE REVIEW

**Comment by n8chur** [comment]
I can try to split this into smaller diffs if need be.

**Comment by AttilaTheFun** [comment]
Thanks for putting this up! If possible could you break it down into some smaller, more easily reviewable commits? Or preferably, separate PRs? Like, the allOf changes could be one PR. We don't have to tag a new version until all the prs are merged.

**Comment by n8chur** [comment]
Yeah, I'll try to break it down into smaller diffs. It is exceptionally large at the moment. I'll try to get to that asap.

**Comment by n8chur** [comment]
Opened #6 with just `allOf` support. The rest will come in follow-up diffs.

**Comment by AttilaTheFun** [comment]
Awesome thanks

**Pull request closed without merging**
